# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Musicsearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Musicsearch
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  target 'MusicsearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicsearchUITests' do
    # Pods for testing
  end

end
